### ISSUE TITLE
Add "Daily Status Report"

### ISSUE THREAD

**Issue by cflsdeboer** [cfl/issues_pims#11]
The point here is to provide an equivalent output report to what is seen in the Central website as the "Daily Status Report".   

When people click this button they will see a page that has a date input. 

Once the button is clicked they will see the 3-part date picker.  (Like in the History of many areas)

When they have selected a date or range then a list of all the distributed transactions from that day will be shown, in their summary format.

All distributions sent out during the Eastern timezone day count.  From 00:00:00 to 23:59:59 Eastern

**Comment by aquiceno** [comment]
Implemented.
