### ISSUE TITLE
Contracts screen Follow up 

### ISSUE THREAD

**Issue by aquiceno** [cfl/issues_pims#21]
- Focus should default to search.
- If team list last touched contracts, if not team list the contracts waiting for approval
- Join text Cornerback and quarterback in a single word (without space)
- Put the $ sign in front of the bonus amount, not behind

**Comment by mstacey80** [comment]
fixes contained in commit: 
ae1d0d1c119175b33e821435e460eeb0ffc83df6 [ae1d0d1]

last item will be worked on with bonus wording.  This is also changable after launch through the PIMS app
