### ISSUE TITLE
Bonus Follow up

### ISSUE THREAD

**Issue by aquiceno** [cfl/issues_pims#28]
1. Delete Signing Bonus 1 
2. Delete Game Bonus 7
3. Game Bonus 6 is the same as Game Bonus 1
4. Game Bonus 5 is the same as Game Bonus 1
5. Games Bonus 3 is the same as Game Bonus 1
6. Total Games needs to be adjustable in Game Bonus 2
7. Outstanding Bonus 1 and 2 are the same
8. Housing Allowance Bonus should have is its own category as it is  a living expense bonus and the most commonly used bonus, and it has option language.

**Comment by mstacey80** [comment]
1,2,6,8 fixed
